App\Entity\User:
  attributes:
      id:
          groups: ['user']

      nombre:

          groups: ['user'] 
      
      apellido:

          groups: ['user'] 
      
      email:
        
          groups: ['user'] 
      
        